CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id UUID NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  company_id BIGINT NULL,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) DEFAULT '',
  secondary_phone VARCHAR(50) DEFAULT '',
  business_name VARCHAR(255) DEFAULT '',
  address TEXT NULL,
  logo TEXT NULL,
  role VARCHAR(40) NOT NULL DEFAULT 'admin' CHECK (role IN ('super_admin', 'admin')),
  status VARCHAR(40) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  failed_login_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_user_id UUID NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_auth_user_id ON users(auth_user_id) WHERE auth_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS login_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  status VARCHAR(80) NOT NULL,
  user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(40) NOT NULL UNIQUE,
  company_id BIGINT NULL,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) DEFAULT '',
  email VARCHAR(255) NULL,
  balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS jewelry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(40) NOT NULL,
  company_id BIGINT NULL,
  material_type VARCHAR(40) NOT NULL DEFAULT 'gold' CHECK (material_type IN ('gold', 'silver', 'diamond')),
  name VARCHAR(255) NOT NULL,
  category VARCHAR(40) NOT NULL DEFAULT 'other' CHECK (category IN ('rings', 'necklaces', 'bracelets', 'earrings', 'watches', 'other')),
  weight NUMERIC(10, 2) NOT NULL DEFAULT 0,
  price_per_gram NUMERIC(12, 2) NOT NULL DEFAULT 0,
  purchase_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  sale_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  quantity INTEGER NOT NULL DEFAULT 1,
  status VARCHAR(40) NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'reserved', 'sold', 'out_of_stock')),
  photo TEXT NULL,
  created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_jewelry_code_company UNIQUE (code, company_id)
);

CREATE TABLE IF NOT EXISTS deposits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NULL,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  amount NUMERIC(12, 2) NOT NULL,
  document_number VARCHAR(40) NOT NULL,
  note TEXT NULL,
  created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NULL,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  jewelry_id BIGINT NULL REFERENCES jewelry(id) ON DELETE SET NULL,
  document_number VARCHAR(40) NOT NULL,
  total_price NUMERIC(12, 2) NOT NULL,
  paid_from_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(40) NOT NULL DEFAULT 'Espèces',
  paid_cash NUMERIC(12, 2) NOT NULL DEFAULT 0,
  paid_mobile_money NUMERIC(12, 2) NOT NULL DEFAULT 0,
  paid_card NUMERIC(12, 2) NOT NULL DEFAULT 0,
  paid_other NUMERIC(12, 2) NOT NULL DEFAULT 0,
  remaining_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  change_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  change_to_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE sales ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS payment_method VARCHAR(40) NOT NULL DEFAULT 'Espèces';
UPDATE sales
SET
  paid_amount = COALESCE(NULLIF(paid_amount, 0), COALESCE(paid_cash, 0) + COALESCE(paid_mobile_money, 0) + COALESCE(paid_card, 0) + COALESCE(paid_other, 0)),
  payment_method = CASE
    WHEN payment_method IS NOT NULL AND payment_method <> '' AND payment_method <> 'Espèces' THEN payment_method
    WHEN (
      (CASE WHEN COALESCE(paid_cash, 0) > 0 THEN 1 ELSE 0 END) +
      (CASE WHEN COALESCE(paid_mobile_money, 0) > 0 THEN 1 ELSE 0 END) +
      (CASE WHEN COALESCE(paid_card, 0) > 0 THEN 1 ELSE 0 END) +
      (CASE WHEN COALESCE(paid_other, 0) > 0 THEN 1 ELSE 0 END) +
      (CASE WHEN COALESCE(paid_from_balance, 0) > 0 THEN 1 ELSE 0 END)
    ) > 1 THEN 'Mixte'
    WHEN COALESCE(paid_from_balance, 0) > 0 AND COALESCE(paid_cash, 0) + COALESCE(paid_mobile_money, 0) + COALESCE(paid_card, 0) + COALESCE(paid_other, 0) = 0 THEN 'Crédit client'
    WHEN COALESCE(paid_mobile_money, 0) > 0 THEN 'Mobile Money'
    WHEN COALESCE(paid_card, 0) > 0 THEN 'Carte'
    WHEN COALESCE(paid_other, 0) > 0 THEN 'Autre'
    ELSE 'Espèces'
  END
WHERE COALESCE(paid_amount, 0) = 0;

CREATE TABLE IF NOT EXISTS sale_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  jewelry_id BIGINT NOT NULL REFERENCES jewelry(id) ON DELETE CASCADE,
  jewelry_code VARCHAR(40) NOT NULL,
  jewelry_name VARCHAR(255) NOT NULL,
  material_type VARCHAR(40) NOT NULL DEFAULT 'gold',
  weight NUMERIC(10, 2) NOT NULL DEFAULT 0,
  price_per_gram NUMERIC(12, 2) NOT NULL DEFAULT 0,
  quantity INTEGER NOT NULL DEFAULT 1,
  line_total NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NULL,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  jewelry_id BIGINT NOT NULL REFERENCES jewelry(id) ON DELETE CASCADE,
  document_number VARCHAR(40) NOT NULL,
  deposit_amount NUMERIC(12, 2) NOT NULL,
  remaining_amount NUMERIC(12, 2) NOT NULL,
  created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NULL,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  operation_type VARCHAR(60) NOT NULL CHECK (
    operation_type IN (
      'deposit_credit',
      'sale_balance_debit',
      'balance_adjustment_credit',
      'balance_adjustment_debit'
    )
  ),
  operation_id BIGINT NULL,
  document_number VARCHAR(40) NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  balance_before NUMERIC(12, 2) NOT NULL,
  balance_after NUMERIC(12, 2) NOT NULL,
  created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_clients_company ON clients(company_id);
CREATE INDEX IF NOT EXISTS idx_jewelry_company_status ON jewelry(company_id, status);
CREATE INDEX IF NOT EXISTS idx_deposits_company_created_at ON deposits(company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_company_created_at ON sales(company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reservations_company_created_at ON reservations(company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_jewelry ON sale_items(jewelry_id);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_client_created_at ON wallet_transactions(client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_company_created_at ON wallet_transactions(company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_operation ON wallet_transactions(operation_type, operation_id);
